# syntax=docker/dockerfile:1

# Use one small Debian-based Node image for all stages. Alpine is smaller, but
# Debian slim avoids native-binary surprises with build tools such as Buf and
# Next's compiler packages.
FROM node:24-slim AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

# Install dependencies in their own stage. Docker can reuse this layer whenever
# package.json and package-lock.json have not changed.
FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

# Build the app in a throwaway stage. This stage has dev dependencies available
# for Buf code generation and Next's production build.
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Generate TypeScript from proto before building so the generated client stays
# in sync with proto/controlpanel/v1/control_panel.proto.
RUN npm run proto:gen

# next.config.ts enables output: "standalone", so this writes a minimal runtime
# tree to .next/standalone plus static assets under .next/static.
RUN npm run build

# Final runtime image. It receives only the standalone server, static assets,
# public files, and Node itself. Source files and dev dependencies stay behind.
FROM base AS runner
ENV NODE_ENV=production
ENV PORT=3000

# Run as a non-root user inside the container. The numeric ids keep ownership
# stable even if names differ across environments.
RUN groupadd --system --gid 1001 nodejs \
  && useradd --system --uid 1001 --gid nodejs nextjs

# The standalone output includes server.js and only the traced runtime files.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Next's standalone output does not include public/ or .next/static by default,
# so copy them beside server.js for the minimal server to serve.
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

# server.js is generated by Next's standalone build. It is smaller than running
# `next start` because it does not require the full Next CLI or source tree.
CMD ["node", "server.js"]
