syntax = "proto3";

package controlpanel.v1;

service SignalStimService {
  rpc SetSignal(SignalsRequest) returns (SignalsResponse);
  rpc RemoveSignals(SignalsRequest) returns (SignalsResponse);
  rpc ResetAll(Empty) returns (ResponseStatus);
}

enum Status {
  STATUS_SUCCESS = 0;
  STATUS_FAILURE = 1;
}

enum CardModel {
  CARD_MODEL_TYPE1 = 0;
  CARD_MODEL_TYPE2 = 1;
}

message Signal {
  uint64 signal_id = 1;
  CardModel card_model = 2;

  oneof signal_value {
    bool discrete = 3;
    uint32 analog = 4;
    string serial = 5;
  }
}

message SignalsRequest {
  repeated Signal signals = 1;
}

message SignalError {
  Signal signal = 1;
  repeated string signal_errors = 2;
}

message SignalsResponse {
  ResponseStatus response_status = 1;
  repeated SignalError signal_errors = 2;
}

message ResponseStatus {
  Status status = 1;
}

message Empty {}
